name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: list files
        run: ls -alR

      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > static/version.json'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Run build task for assets
        run: npm run build

      - name: Create tar
        run: tar --exclude='*.example' -czf ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}.tar.gz ./app ./jinja2 ./static

      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}
          path: ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}.tar.gz
