name: Create release package

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: list files
        run: ls -alR

      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > static/version.json'

      - name: Create tar
        run: tar -czf ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}.tar.gz ./app ./jinja2 ./static

      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}
          path: ${{ github.event.repository.name }}_${{ env.RELEASE_VERSION }}.tar.gz
